# Generated by Django 6.0 on 2025-12-31 13:06

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_submissions(apps, schema_editor):
    Submission = apps.get_model("assessments", "Submission")
    # For each student/exam pair, keep the earliest submission (by started_at then id) and delete others
    from django.db.models import Min

    # Find duplicates
    pairs = (
        Submission.objects.values("student_id", "exam_id")
        .annotate(cnt=models.Count("id"))
        .filter(cnt__gt=1)
    )

    for p in pairs:
        student_id = p["student_id"]
        exam_id = p["exam_id"]
        subs = Submission.objects.filter(student_id=student_id, exam_id=exam_id).order_by("started_at", "id")
        # keep first
        keep = subs.first()
        # delete others
        subs.exclude(id=keep.id).delete()



class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_submissions, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("student", "exam")},
        ),
    ]
